#' @name mertic_formatting
#' @rdname mertic_formatting
#'
#' @title Various metric formatting function
#'
#' @param x A data frame generated by Prometheus query
#'
#' @return Formatted metrics object
NULL

#' @section Utility function for parsing metrics output:
#'   Formats metrics data from the current query
#' @rdname mertic_formatting
format_metrics_instant_data <- function(x) {
  # Clean column names
  x <- rename_metrics_data_frame(x)
  within(data = x,
         expr = {
           port = as.integer(gsub(
             pattern = "(.*):(.*)",
             replacement = "\\2",
             x = instance
           ))

           instance = gsub(pattern = "(.*):(.*)",
                           replacement = "\\1",
                           x = instance)

           value = destring(value)
         })
}

#' @section Utility function for parsing range metrics output:
#'   Formats metrics data passed by range query.
#' @rdname mertic_formatting
format_metrics_range_data <- function(x) {
  checkmate::assert_data_frame(x = x,
                               min.rows = 1,
                               min.cols = 2)
  # Clean column names
  x <- rename_metrics_data_frame(x)
  x_metrics <- within(data = x$metric,
                      expr = {
                        port = as.integer(gsub(
                          pattern = "(.*):(.*)",
                          replacement = "\\2",
                          x = instance
                        ))

                        instance = gsub(pattern = "(.*):(.*)",
                                        replacement = "\\1",
                                        x = instance)
                      })

  dfs_to_bind <- lapply(
    X = x$values,
    FUN = function(value_pair) {
      setNames(object = as.data.frame(value_pair),
               nm = c("timestamp", "value")) -> df_ts_val
    }
  )

  i <- 1
  res <- Reduce(rbind,
                lapply(
                  X = dfs_to_bind,
                  FUN = function(dfs) {
                    x <- suppressWarnings(cbind(x_metrics[i,], dfs))
                    i <<- i + 1
                    x
                  }
                ))

  res <- within(data = res,
                expr = {
                  value = destring(value)
                })

  return(res)
}

#' @section Utility function for parsing metadata output:
#'   Formats data passed by metadata query.
#' @rdname mertic_formatting
format_metadata <- function(x) {
  checkmate::assert_data_frame(x = x,
                               min.rows = 1,
                               min.cols = 2)

  res <- rename_metadata_data_frame(x)

  return(res)
}
